# Generated by Django 4.1 on 2022-08-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restauraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restauraunt_name', models.CharField(help_text='Введите название заведения', max_length=50)),
            ],
            options={
                'ordering': ['restauraunt_name'],
            },
        ),
    ]
