# Generated by Django 4.1 on 2022-08-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='callory',
            field=models.FloatField(blank=True, null=True, verbose_name='Каллории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(blank=True, null=True, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='grams',
            field=models.FloatField(blank=True, null=True, verbose_name='Граммы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если старой цены нету, заполните только новую цену', max_digits=9, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='Белки'),
        ),
    ]
