# Generated by Django 4.1 on 2022-08-07 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauraunt',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='restauraunt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
