# Generated by Django 4.1 on 2022-08-08 00:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_restauraunt_created_at_restauraunt_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Введите название категории', max_length=50)),
                ('photo', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='restauraunt',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='restauraunt',
            old_name='restauraunt_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='ToppingGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Введите название группы топпингов', max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='restauraunt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restauraunt'),
        ),
    ]
