# Generated by Django 4.1 on 2022-08-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_product_callory_alter_product_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если старой цены нету, заполните только новую цену', max_digits=9, null=True, verbose_name='Старая цена'),
        ),
    ]
