# Generated by Django 4.1 on 2022-08-08 00:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_alter_restauraunt_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='restauraunt_id',
            new_name='restauraunt',
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Введите название топпинга', max_length=50)),
                ('price', models.FloatField(help_text='Введите цену топпинга')),
                ('topping_groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.toppinggroups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
