# Generated by Django 4.1 on 2022-09-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Если старой цены нету, заполните только новую цену', max_digits=9, null=True, verbose_name='Старая цена'),
        ),
    ]
