# Generated by Django 4.1 on 2022-08-08 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_restauraunt_id_category_restauraunt_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppinggroups',
            old_name='category_id',
            new_name='category',
        ),
    ]
