# Generated by Django 4.1 on 2022-08-09 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_category_slug_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauraunt',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
